name: cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: cover
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/Naninovel/index.json -n github --username ${{ github.repository_owner }} --password ${{ github.token }}
          dotnet test backend/Naninovel.Language.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
