name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: cover
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/naninovel/index.json -n github --username ${{ secrets.GH_USER }} --password ${{ secrets.GH_TOKEN }} --store-password-in-clear-text
          dotnet workload restore backend/Naninovel.Language.sln
          dotnet test backend /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet publish backend
          npm ci
          npm run build
          npm run cover
      - name: upload coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
